###
POST http://localhost:8080/transformPattern
Content-Type: application/json

{
  "scope": "Globally",
  "pattern": "Universality",
  "patternProps": {
    "event": "Event1",
    "timeBound": "valueT",
    "probabilityBound": "valueP"
  },
  "events": [
    {
      "name": "Event1",
      "specification": "testSpecification"
    }
  ],
  "targetLogic": "LTL"
}